public class ejercicio18{
    public static void solucion(){
        //variables cogidas de fuera para ver si puedo dividir dos integer y sacar un decimal.
        Integer a = 12;
        Integer b = 4;

        Decimal promedio = (a + b)/2;
        System.debug('El promedio de las dos variables es: ' + promedio);

        Decimal x = 12.5;
        Decimal y = 3.75;

        promedio = (x + y)/2; 
        System.debug('El promedio de las dos variables es: ' + promedio);
    }
}