/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-19-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// Crea una página Visualforce que muestre un mensaje simple:
// Muestra el texto: "¡Bienvenido, Iosu, al entrenamiento Jedi en Visualforce!" en un encabezado <h1>. 


<apex:page >
    <h1>
        ¡Bienvenido, Iosu, al entrenamiento intensivo en Visualforce!
    </h1>
</apex:page>
